# Generated by Django 4.2.3 on 2023-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="time_section",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
